server:
  port: 7001
spring:
  application:
    name: my-blog-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置Sentinel的地址
        dashboard: localhost:8080



  datasource:
    url: jdbc:mysql://localhost:3306/myblog_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 25
      max-wait: 60000
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 60000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql语句
    map-underscore-to-camel-case: true #开启数据库的驼峰映射
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xingbingxuan.blog.client.entity #开启实体类的别名

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

