server:
  port: 8001
spring:
  application:
    name: my-blog-admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置Sentinel的地址
        dashboard: localhost:8080